steps:
- name: 'gcr.io/cloud-builders/go'
  args: ['install', './src']
  env: ['PROJECT_ROOT=github.com/regisoda/codeedu-maratona-desafio-ci']
# - name: 'gcr.io/cloud-builders/go'
#   args: ['test', 'src']
#   env: ['PROJECT_ROOT=src']
# - name: 'gcr.io/cloud-builders/docker'
#   args: ['build', '--tag=gcr.io/$PROJECT_ID/go-desafio-ci', '.']
# images: ['gcr.io/$PROJECT_ID/go-desafio-ci']