steps:
- id: "go install"
  name: 'gcr.io/cloud-builders/go'
  args: ['install', './src']
  env: ['PROJECT_ROOT=github.com/regisoda/codeedu-maratona-desafio-ci']
- id: "go test"
  name: 'gcr.io/cloud-builders/go'
  args: ['test', './src']
  env: ['PROJECT_ROOT=github.com/regisoda/codeedu-maratona-desafio-ci']
- id: "docker build"
  name: 'gcr.io/cloud-builders/docker'
  args: ['build', '--tag=gcr.io/$PROJECT_ID/go-desafio-ci', './Dockerfile.cloudbuild']
images: ['gcr.io/$PROJECT_ID/go-desafio-ci']